### ISSUE TITLE
Add features to mercury-sdk

### ISSUE THREAD

**Issue by chopan123** [paltalabs/mercury-sdk#18]
- [ ] Add support for contract entries
    - [ ] Fix function to subscribe to contract entries (add durability)
    - [ ] Add a special case for `KEY_XDR="AAAFA=="` to subscribe to instance storage (with durability="persistent")
    - [ ] Add function to retrieve information from contract entries with its query
  - [ ] Factory contract
    - [ ] Use previous function to get entries from factory contract
    - [ ] Add parseFactoryInstanceEntry function, special attention with `value_xdr` to get the pair addresses of all pairs
  - [ ] Pair contract
    - [ ] Use previous function to get entries from pair contract
    - [ ] Add parsePairInstanceEntry function, special attention `value_xdr` to get the reserves

**Comment by esteblock** [comment]
@MattPoblete plese check if we can close this issue

**Comment by esteblock** [comment]
Solved in https://github.com/paltalabs/mercury-sdk/pull/20
